# Tensorflow tf.data API

In [21]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers

In [2]:
data = pd.read_csv("heart.csv")
data.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [43]:
file_data = tf.keras.utils.get_file(origin="https://www.kaggle.com/datasets/fedesoriano/heart-failure-prediction?select=heart.csv")

In [45]:
column_names = ["age", "sex", "cp", "trestbps", "chol", "fbs", "restecg", "thalach", "exang", "oldpeak", "slope", "ca", "thal", "target"]

heart_csv_ds = tf.data.experimental.make_csv_dataset("heart.csv", 
                                                     batch_size=10,
                                                     num_epochs=1,
                                                    column_names=column_names,
                                                    label_name=column_names[-1],
                                                    header=True,
                                                    shuffle=True)

In [26]:
heart_csv_ds

<PrefetchDataset element_spec=(OrderedDict([('age', TensorSpec(shape=(None,), dtype=tf.int32, name=None)), ('sex', TensorSpec(shape=(None,), dtype=tf.int32, name=None)), ('cp', TensorSpec(shape=(None,), dtype=tf.int32, name=None)), ('trestbps', TensorSpec(shape=(None,), dtype=tf.int32, name=None)), ('chol', TensorSpec(shape=(None,), dtype=tf.int32, name=None)), ('fbs', TensorSpec(shape=(None,), dtype=tf.int32, name=None)), ('restecg', TensorSpec(shape=(None,), dtype=tf.int32, name=None)), ('thalach', TensorSpec(shape=(None,), dtype=tf.int32, name=None)), ('exang', TensorSpec(shape=(None,), dtype=tf.int32, name=None)), ('oldpeak', TensorSpec(shape=(None,), dtype=tf.float32, name=None)), ('slope', TensorSpec(shape=(None,), dtype=tf.int32, name=None)), ('ca', TensorSpec(shape=(None,), dtype=tf.int32, name=None)), ('thal', TensorSpec(shape=(None,), dtype=tf.int32, name=None))]), TensorSpec(shape=(None,), dtype=tf.int32, name=None))>

In [27]:
for batch, label in heart_csv_ds.take(1):
    for key, value in batch.items():
        print(f"{key:20s}: {value}")
    print("\n", f"{'label':20s}: {label}")

age                 : [63 59 47 55 60 62 50 50 62 54]
sex                 : [1 1 1 1 1 0 1 1 0 1]
cp                  : [0 0 2 0 0 2 0 2 0 2]
trestbps            : [130 110 130 132 125 130 150 129 150 125]
chol                : [330 239 253 353 258 263 243 196 244 273]
fbs                 : [1 0 0 0 0 0 0 0 0 0]
restecg             : [0 0 1 1 0 1 0 1 1 0]
thalach             : [132 142 179 132 141  97 128 163 154 152]
exang               : [1 1 0 1 1 0 0 0 1 0]
oldpeak             : [1.8 1.2 0.  1.2 2.8 1.2 2.6 0.  1.4 0.5]
slope               : [2 1 2 1 1 1 1 2 1 0]
ca                  : [3 1 0 1 1 1 0 0 0 1]
thal                : [3 3 2 3 3 3 3 2 2 2]

 label               : [0 0 1 0 0 0 0 1 0 1]


In [28]:
%%time
for i, (batch, label) in enumerate(heart_csv_ds.repeat(20)):
    if i % 40 == 0:
        print('.', end='')
print()

................
CPU times: total: 1.5 s
Wall time: 888 ms


In [42]:
for element, label in heart_csv_ds.take(1):
    for key, value in element.items():
        print(value)
    print(label)

tf.Tensor([49 51 58 58 44 65 70 67 59 39], shape=(10,), dtype=int32)
tf.Tensor([0 0 1 0 1 1 1 1 0 1], shape=(10,), dtype=int32)
tf.Tensor([1 2 2 0 2 3 1 2 0 2], shape=(10,), dtype=int32)
tf.Tensor([134 140 140 100 120 138 156 152 174 140], shape=(10,), dtype=int32)
tf.Tensor([271 308 211 248 226 282 245 212 249 321], shape=(10,), dtype=int32)
tf.Tensor([0 0 1 0 0 1 0 0 0 0], shape=(10,), dtype=int32)
tf.Tensor([1 0 0 0 1 0 0 0 1 0], shape=(10,), dtype=int32)
tf.Tensor([162 142 165 122 169 174 143 150 143 182], shape=(10,), dtype=int32)
tf.Tensor([0 0 0 0 0 0 0 0 1 0], shape=(10,), dtype=int32)
tf.Tensor([0.  1.5 0.  1.  0.  1.4 0.  0.8 0.  0. ], shape=(10,), dtype=float32)
tf.Tensor([1 2 2 1 2 1 2 1 1 2], shape=(10,), dtype=int32)
tf.Tensor([0 1 0 0 0 1 0 0 0 0], shape=(10,), dtype=int32)
tf.Tensor([2 2 2 2 2 2 2 3 2 2], shape=(10,), dtype=int32)
tf.Tensor([1 1 1 1 1 0 1 0 0 1], shape=(10,), dtype=int32)


In [58]:
iterator = heart_csv_ds.as_numpy_iterator()
print(next(iterator))

(OrderedDict([('age', array([58, 43, 55, 56, 45, 61, 58, 71, 61, 64])), ('sex', array([0, 0, 1, 0, 1, 1, 0, 0, 1, 1])), ('cp', array([0, 2, 0, 0, 0, 2, 1, 1, 0, 3])), ('trestbps', array([100, 122, 160, 134, 104, 150, 136, 160, 138, 170])), ('chol', array([248, 213, 289, 409, 208, 243, 319, 302, 166, 227])), ('fbs', array([0, 0, 0, 0, 0, 1, 1, 0, 0, 0])), ('restecg', array([0, 1, 0, 0, 0, 1, 0, 1, 0, 0])), ('thalach', array([122, 165, 145, 150, 148, 137, 152, 162, 125, 155])), ('exang', array([0, 0, 1, 1, 1, 1, 0, 0, 1, 0])), ('oldpeak', array([1. , 0.2, 0.8, 1.9, 3. , 1. , 0. , 0.4, 3.6, 0.6], dtype=float32)), ('slope', array([1, 1, 1, 1, 1, 1, 2, 2, 1, 1])), ('ca', array([0, 0, 1, 2, 0, 0, 2, 2, 1, 0])), ('thal', array([2, 2, 3, 3, 2, 2, 2, 2, 2, 3]))]), array([1, 1, 0, 0, 1, 1, 0, 1, 0, 1]))


In [94]:
model = tf.keras.Sequential([
  layers.Dense(128, activation='relu', input_shape=(1,)),
  layers.Dense(128, activation='relu'),
  layers.Dropout(.1),
  layers.Dense(1)
])

model.compile(optimizer='adam',
              loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
              metrics=['accuracy'])

In [95]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_12 (Dense)            (None, 128)               256       
                                                                 
 dense_13 (Dense)            (None, 128)               16512     
                                                                 
 dropout_4 (Dropout)         (None, 128)               0         
                                                                 
 dense_14 (Dense)            (None, 1)                 129       
                                                                 
Total params: 16,897
Trainable params: 16,897
Non-trainable params: 0
_________________________________________________________________


In [134]:
heart_ds = tf.data.Dataset

In [135]:
heart_ds

tensorflow.python.data.ops.dataset_ops.DatasetV2

In [136]:
for element, label in heart_csv_ds.take(1):
    for key, value in element.items():
        heart_ds = heart_ds.from_tensor_slices((value, label))

In [137]:
heart_ds

<TensorSliceDataset element_spec=(TensorSpec(shape=(), dtype=tf.int32, name=None), TensorSpec(shape=(), dtype=tf.int32, name=None))>

In [141]:
for element, label in heart_csv_ds.take(-1):
    heart_features_dict = {name: np.array(value)
                         for name, value in element.items()}

In [142]:
heart_features_dict

{'age': array([60, 50, 48]),
 'sex': array([1, 1, 1]),
 'cp': array([0, 0, 0]),
 'trestbps': array([125, 144, 124]),
 'chol': array([258, 200, 274]),
 'fbs': array([0, 0, 0]),
 'restecg': array([0, 0, 0]),
 'thalach': array([141, 126, 166]),
 'exang': array([1, 1, 0]),
 'oldpeak': array([2.8, 0.9, 0.5], dtype=float32),
 'slope': array([1, 1, 1]),
 'ca': array([1, 0, 0]),
 'thal': array([3, 3, 3])}

In [144]:
heart_ds = tf.data.Dataset.from_tensor_slices(heart_features_dict)
heart_ds

<TensorSliceDataset element_spec={'age': TensorSpec(shape=(), dtype=tf.int32, name=None), 'sex': TensorSpec(shape=(), dtype=tf.int32, name=None), 'cp': TensorSpec(shape=(), dtype=tf.int32, name=None), 'trestbps': TensorSpec(shape=(), dtype=tf.int32, name=None), 'chol': TensorSpec(shape=(), dtype=tf.int32, name=None), 'fbs': TensorSpec(shape=(), dtype=tf.int32, name=None), 'restecg': TensorSpec(shape=(), dtype=tf.int32, name=None), 'thalach': TensorSpec(shape=(), dtype=tf.int32, name=None), 'exang': TensorSpec(shape=(), dtype=tf.int32, name=None), 'oldpeak': TensorSpec(shape=(), dtype=tf.float32, name=None), 'slope': TensorSpec(shape=(), dtype=tf.int32, name=None), 'ca': TensorSpec(shape=(), dtype=tf.int32, name=None), 'thal': TensorSpec(shape=(), dtype=tf.int32, name=None)}>

In [138]:
EPOCHS = 5   
model.fit(heart_ds, epochs=EPOCHS)

Epoch 1/5


TypeError: 'NoneType' object is not callable